name: Deploy Apps

on:
  # For main branch, we run after tests pass
  workflow_run:
    workflows: ["Test Apps"]
    types:
      - completed
    branches: [main]
  # For PRs, we run directly on changes
  pull_request:
    types: [opened, synchronize, reopened, closed]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    if: |
      (github.event_name == 'pull_request' && github.event.action != 'closed') ||
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install root dependencies
        run: npm install

      - name: Show initial directory structure
        run: |
          echo "Current directory structure:"
          tree -L 3 || (apt-get update && apt-get install -y tree && tree -L 3)

      - name: Build all apps
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            npm run build pr-preview ${{ github.event.pull_request.number }}
            echo "PR Preview build output structure:"
            tree pr-preview -L 3
          else
            npm run build _site
            echo "_site build output structure:"
            tree _site -L 3
          fi

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ${{ github.event_name == 'pull_request' && './pr-preview' || './_site' }}

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2

      - name: Comment PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          script: |
            const baseUrl = 'https://pollinations.github.io/hive/pr-${{ github.event.pull_request.number }}/';
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `🚀 PR Preview deployed!\n\nPreview URL: ${baseUrl}`
            })

  cleanup-preview:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Create empty PR preview directory
        run: mkdir -p pr-${{ github.event.pull_request.number }}
          
      - name: Upload empty artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: pr-${{ github.event.pull_request.number }}

      - name: Deploy empty directory
        id: deployment
        uses: actions/deploy-pages@v2